export const home = [
    'getting-started',
    'release-notes',
    'sonolus.js-guide',
    'sonolus.py-guide',
    'custom-server-specs',
    'round-multiplayer-server-specs',
    'level-specs',
    'replay-specs',
    'skin-specs',
    'background-specs',
    'effect-specs',
    'particle-specs',
    'engine-specs',
]
